plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.apiverve'
version = '1.1.14'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    implementation 'org.json:json:20231013'
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'com.apiverve'
            artifactId = 'seovalidator-api'
            version = '1.1.14'

            from components.java

            pom {
                name = 'SEO Quick Validator'
                description = 'SEO Validator is a simple tool for validating SEO metrics. It returns a list of issues that need to be fixed to improve the SEO metrics of a web page.'
                url = 'https://apiverve.com'

                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://opensource.org/licenses/MIT'
                    }
                }

                developers {
                    developer {
                        id = 'apiverve'
                        name = 'APIVerve'
                        email = 'hello@apiverve.com'
                    }
                }

                scm {
                    connection = 'scm:git:git://github.com/apiverve/seovalidator-api.git'
                    developerConnection = 'scm:git:ssh://github.com/apiverve/seovalidator-api.git'
                    url = 'https://github.com/apiverve/seovalidator-api'
                }
            }
        }
    }
}
