// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SEOQuickValidator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("passed")]
        public bool? Passed { get; set; }

        [JsonProperty("issueCount")]
        public long? IssueCount { get; set; }

        [JsonProperty("issues")]
        public string[] Issues { get; set; }

        [JsonProperty("checks")]
        public Checks Checks { get; set; }

        [JsonProperty("seoScore")]
        public long? SeoScore { get; set; }

        [JsonProperty("grade")]
        public string Grade { get; set; }
    }

    public partial class Checks
    {
        [JsonProperty("hasTitle")]
        public bool? HasTitle { get; set; }

        [JsonProperty("titleLength")]
        public long? TitleLength { get; set; }

        [JsonProperty("hasMetaDescription")]
        public bool? HasMetaDescription { get; set; }

        [JsonProperty("metaDescriptionLength")]
        public long? MetaDescriptionLength { get; set; }

        [JsonProperty("hasMetaKeywords")]
        public bool? HasMetaKeywords { get; set; }

        [JsonProperty("h1Count")]
        public long? H1Count { get; set; }

        [JsonProperty("hasCanonical")]
        public bool? HasCanonical { get; set; }

        [JsonProperty("hasViewport")]
        public bool? HasViewport { get; set; }

        [JsonProperty("imagesTotal")]
        public long? ImagesTotal { get; set; }

        [JsonProperty("imagesMissingAlt")]
        public long? ImagesMissingAlt { get; set; }

        [JsonProperty("externalLinksTotal")]
        public long? ExternalLinksTotal { get; set; }

        [JsonProperty("externalLinksMissingRel")]
        public long? ExternalLinksMissingRel { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
